### PR TITLE
Generate rails 6 api only

### LINKED ISSUE #4: create rails 6 api only
We have decided to use rails 6 for this api. Create a new rails api only application

### PR DESCRIPTION
**Pull request by aonomike**
- Ran command `rails new . --api`

Fixes #4

### CODE REVIEW

**Comment by NickSchimek** [comment]
Typically I would also use option `-d=postgresql` to configure for postgres and `-T` so that it doesn't configure any mini-test files. Unless we're going to use minitest?

After that add the `rspec-rails` rails gem, and ensure you get the beta version 4, previous versions have issues with rails 6, and run rspec install command. Then push up.

Let me know what your thoughts are @aonomike

**Comment by aonomike** [comment]
Thanks @NickSchimek let me make the updates and push up.

**Comment by aonomike** [comment]
@NickSchimek from the [rspec changelog](https://github.com/rspec/rspec-rails/blob/master/Changelog.md) seems their latest stable version is 3.8.2. Is that the correct one you suggested.

**Comment by NickSchimek** [comment]
yes, You'll want to use this one here: `gem 'rspec-rails', '~> 4.0.0.beta2'` with rails 6. The previous version will give you issues right out of the box.

**Comment by NickSchimek** [comment]
@aonomike rails 6 is not a stable release yet either.... so I'm assuming that's why rspec_rails 4 is not labeled as a stable release... Once rails 6 is finalized then they'll finalize rspec_rails

**Comment by NickSchimek** [comment]
In the future it will be less confusing. With each rails update then rspec_rails will also update their version number to match rails version number

**Comment by aonomike** [comment]
Made the rspec-rails upgrade @NickSchimek

**Comment by NickSchimek** [comment]
@aonomike PR Looks good to me 👍

**Review by NickSchimek — APPROVED** [review]

**Review by mattwr18 — APPROVED** [review]

**Comment by mattwr18** [comment]
great! thanks @aonomike for this, and @NickSchimek for your excellent code review!!

**Pull request merged**
