### PR TITLE
Implement encrypted credentials

### PR DESCRIPTION
**Pull request by riccardo-giomi**
#### Fixes issue #74

- [x] Tests all green tests and all builds passes :green_heart:
- [x] PR well-named, issue linked :paperclip: and no merge conflicts.
- [x] Request review from other contributors

### CODE REVIEW

**Review by gr1d99 — COMMENTED** [review]
Looks good @riccardo-giomi

It would also be better if you remove [this](https://github.com/AgileVentures/WebsiteOneBackendApi/blob/63eb9aaa09a9ad4755a0ba9bb77e714fa1d13f5f/config/database.yml#L20) and [this](https://github.com/AgileVentures/WebsiteOneBackendApi/blob/63eb9aaa09a9ad4755a0ba9bb77e714fa1d13f5f/config/database.yml#L21) from `database.yml`.

Rails will automatically use the default role which is postgres, unless in special cases where someone might have a different role.

What do you think?

**Comment by riccardo-giomi** [comment]
> It would also be better if you remove [this](https://github.com/AgileVentures/WebsiteOneBackendApi/blob/63eb9aaa09a9ad4755a0ba9bb77e714fa1d13f5f/config/database.yml#L20) and [this](https://github.com/AgileVentures/WebsiteOneBackendApi/blob/63eb9aaa09a9ad4755a0ba9bb77e714fa1d13f5f/config/database.yml#L21) from `database.yml`.
> 
> Rails will automatically use the default role which is postgres, unless in special cases where someone might have a different role.
> 
> What do you think?

I would leave them:

It seems that not having those lines or having them with the enviromental variables not set behaves the same. Leaving those lines would also allow to still install easily where the users for postgres are setup differently.

**Review by aonomike — APPROVED** [review]
Looks good to me. Always appreciated @riccardo-giomi

**Comment by aonomike** [comment]
> Looks good @riccardo-giomi
> 
> It would also be better if you remove [this](https://github.com/AgileVentures/WebsiteOneBackendApi/blob/63eb9aaa09a9ad4755a0ba9bb77e714fa1d13f5f/config/database.yml#L20) and [this](https://github.com/AgileVentures/WebsiteOneBackendApi/blob/63eb9aaa09a9ad4755a0ba9bb77e714fa1d13f5f/config/database.yml#L21) from `database.yml`.
> 
> Rails will automatically use the default role which is postgres, unless in special cases where someone might have a different role.
> 
> What do you think?

I am gonna create a new issue for this as it's not related to encrypted credentials :) thanks @gr1d99 @riccardo-giomi

**Pull request merged**
