### PR TITLE
Add a PR template

### LINKED ISSUE #10: Add PR template
Add PR template to assist contributors have more descriptive PR messages.

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #10

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hey @aonomike @mattwr18 kindly review

**Comment by aonomike** [comment]
Thanks @cesswairimu for working on this, maybe just one suggestion
- Add section for description of the PR just before the `fixes issue` section?

**Comment by cesswairimu** [comment]
Thanks for the review @aonomike...Just added that section. Thanks

**Review by aonomike — APPROVED** [review]
Looks good to me. Thanks @cesswairimu !!!

**Pull request merged**
