### PR TITLE
Refactor Event request spec

### PR DESCRIPTION
**Pull request by NickSchimek**
## Description

Divided the event spec into a file for each action. Dried up the tests a bit.

### CODE REVIEW

**Comment by riccardo-giomi** [comment]
As requested by @NickSchimek I've changed the response of the index request to the events controller so that it looks like this:

```json
{
  "events": [...]
}
```
Please note that this change would require to update the [front-end project](https://github.com/AgileVentures/WebsiteOne-FE) to handle the new response format.

**Comment by aonomike** [comment]
Hi @NickSchimek somehow the build passes on travis but it does not update here. Would you know of the reason? we have tried to have a look with @riccardo-giomi but could not see reason...

**Comment by NickSchimek** [comment]
@aonomike It is a known issue. You can fix it by following the instructions here: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Review by aonomike — APPROVED** [review]
LGTM. I am going to create an issue to add tests for an unauthenticate user. Thanks @riccardo-giomi and @NickSchimek and team for setting great standards!!

**Pull request merged**
