### PR TITLE
Inital commit

### PR DESCRIPTION
**Pull request by mattwr18**
- create rails 5 api with ruby 2.6.1

fixes#1

### CODE REVIEW

**Comment by StlMaris123** [comment]
I think this is good to go

**Comment by mattwr18** [comment]
Actually, I think we have decided to use Rails 6... @ciremoussadia was a dissenting voice, so we might want to see that he is ok with it, but everyone else is keen to use 6... 
So then we can upgrade this, which would be more work, but would provide learning, as you pointed out, or we could create a new rails 6 api only and put in a different `PR`
What do you think?

**Comment by ciremoussadia** [comment]
@mattwr18 @StlMaris123 I'm fine with upgrading to rails 6.

**Review by aonomike — APPROVED** [review]
Looks good!!! Thanks @mattwr18

**Comment by mattwr18** [comment]
Thanks @aonomike, but I think the idea is to close this and open. A new one with Rails 6 since that is the consensus we reached.

**Pull request closed without merging**
